spring.application.name=property-service
spring.datasource.url=jdbc:postgresql://localhost:5433/propertyflow
spring.datasource.username=propertyflow
spring.datasource.password=propertyflow

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true